# This is an example mods.toml file.
# Any fields that aren't annotated with #optional are *required*!
modLoader = "javafml"
loaderVersion = "[43,)"
license = "All rights reserved" # Want to make your mod open source? Check out https://choosealicense.com/!

# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
# issueTrackerURL="https://github.com/invalid/pleasechangeme/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]]
modId = "ars_artifice"
# The version number of the mod - unlike in the Forge MDK,
# we'll use the processResources task to replace this for us
version = "${version}"
displayName = "Ars Artifice"
# This URL will be queried by the Forge update checker in order to find the latest version of your mod.
# If an update is found, you'll see a little blinking "emerald" symbol on your Mods button!
# updateJSONURL="https://changeme.dev/updates.json" #optional
# This is your mod's "homepage" and will be displayed on the mod's information screen in the Mods panel.
# displayURL="https://changeme.dev/" #optional
# This will be displayed as your mod's logo in the Mods panel.
# logoFile="icon.png" #optional
# Some more fluff displayed in the Mods panel. Feel free to issue your special thanks here!
# credits="Thanks to Mojang for making this great game" #optional
# Some more fluff displayed in the Mods panel. Plug your stuff here!
# authors="Me!" #optional
# A multi-line description for your mod. This has no minimum length, but it *is* required!
description = '''
This is a very cool mod that does... things.

...and stuff.

Have I reached 280 characters yet?
'''

# An (optional) dependency for your mod. Though technically not required,
# it's always helpful to add these to stop your mod from loading when something is missing
# rather than erroring out later
[[dependencies.ars_artifice]] #optional
# the modid of the dependency
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[40.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
# Here's another dependency
[[dependencies.ars_artifice]]
modId="patchouli"
mandatory=true
versionRange="[1.18.1-61,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ars_artifice]]
modId="curios"
mandatory=true
versionRange="[1.18.1-5.0.3.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ars_artifice]]
modId="ars_nouveau"
mandatory=true
versionRange="[2.5.0,)"
ordering="AFTER"
side="BOTH"
[dependencies.ars_artifice.custom.mc-publish]
ignore=false
curseforge="ars-nouveau" # CurseForge's project slug

